// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBGy9TFvc-SzsdJAsp96bfwj3bcnvRaM0',
    appId: '1:82925868746:web:df6ad1f49927bd560e4633',
    messagingSenderId: '82925868746',
    projectId: 'ichkili-51ddf',
    authDomain: 'ichkili-51ddf.firebaseapp.com',
    storageBucket: 'ichkili-51ddf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARANAzSSQwemXh6lj4Vj3HoibKWglvoU8',
    appId: '1:82925868746:android:c2e1ac78599975e60e4633',
    messagingSenderId: '82925868746',
    projectId: 'ichkili-51ddf',
    storageBucket: 'ichkili-51ddf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx28TaU9HpTvJ2LB1_IzVglURwGdjEkeQ',
    appId: '1:82925868746:ios:eb1e8a53384416e00e4633',
    messagingSenderId: '82925868746',
    projectId: 'ichkili-51ddf',
    storageBucket: 'ichkili-51ddf.appspot.com',
    iosBundleId: 'com.example.ichkili',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx28TaU9HpTvJ2LB1_IzVglURwGdjEkeQ',
    appId: '1:82925868746:ios:eb1e8a53384416e00e4633',
    messagingSenderId: '82925868746',
    projectId: 'ichkili-51ddf',
    storageBucket: 'ichkili-51ddf.appspot.com',
    iosBundleId: 'com.example.ichkili',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBGy9TFvc-SzsdJAsp96bfwj3bcnvRaM0',
    appId: '1:82925868746:web:0b6475c085d8f8850e4633',
    messagingSenderId: '82925868746',
    projectId: 'ichkili-51ddf',
    authDomain: 'ichkili-51ddf.firebaseapp.com',
    storageBucket: 'ichkili-51ddf.appspot.com',
  );
}
